# Dockerfile.dev

# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Copy environment variables
COPY .env.development .env

# Expose port 3000
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
